# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Keep card information file updated

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force update even if DB version is up to date'
        required: true
        type: choice
        default: 'false'
        options: 
        - 'true'
        - 'false'
  schedule:
    - cron: '0 9 * * *'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  keep_cardinfo_update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run updateCardInfo -- ${{ inputs.force }}
